name: Armis SDK Tests

# This GitHub action runs your tests for each pull request and push.
on:
  pull_request:
    paths:
      - "armis/**.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/sdk-tests.yml"
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Harden the runner (Block egress)
        uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # v2.18.0
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            objects.githubusercontent.com:443
            codeload.github.com:443
            raw.githubusercontent.com:443
            release-assets.githubusercontent.com:443
            proxy.golang.org:443
            sum.golang.org:443

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: 'go.mod'
          cache: true
      - run: go mod tidy
      - run: go mod download
      - run: go build -v ./...

  sdk-tests:
    name: Armis SDK Unit Tests
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Harden the runner (Block egress)
        uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # v2.18.0
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            objects.githubusercontent.com:443
            codeload.github.com:443
            raw.githubusercontent.com:443
            release-assets.githubusercontent.com:443
            proxy.golang.org:443
            sum.golang.org:443

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Download Dependencies
        run: go mod download
      - name: Run SDK Tests
        run: go test -v -race -coverprofile=coverage.out ./armis/... | tee sdk-test.log
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: sdk-test-log
          path: sdk-test.log
      - name: Upload Coverage
        if: success()
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: coverage
          path: coverage.out
